manifest:
  remotes:
    - name: duanexavierbondad
      url-base: https://github.com/duanexavierbondad
  projects:
    - name: zmk
      remote: duanexavierbondad
      revision: caksoylar/experimental
      import: app/west.yml
  self:
    path: config
