manifest:
  remotes:
    - name: caksoylar
      url-base: https://github.com/duanexavierbondad
  projects:
    - name: zmk
      remote: caksoylar
      revision: caksoylar/experimental
      import: app/west.yml
  self:
    path: config
